// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DataSender is an autogenerated mock type for the DataSender type
type DataSender struct {
	mock.Mock
}
